# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-21 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=20)),
                ('info', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('score', models.FloatField()),
                ('isAdmin', models.BooleanField(default=False)),
                ('isBlocked', models.BooleanField(default=False)),
            ],
        ),
    ]
