# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-24 16:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('cover', models.CharField(max_length=100)),
                ('ISBN', models.CharField(max_length=100)),
                ('press', models.CharField(max_length=100)),
                ('pressTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('grade', models.FloatField(default=5.0)),
                ('gradeNum', models.IntegerField(default=0)),
                ('intro', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=3000)),
                ('starNum', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='labelList',
            field=models.ManyToManyField(to='Book.Tag'),
        ),
        migrations.AddField(
            model_name='book',
            name='reviewList',
            field=models.ManyToManyField(to='Book.Review'),
        ),
    ]
