# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-26 10:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_userinfo_collectionlist'),
        ('Book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='labelList',
            field=models.ManyToManyField(default=[], to='Book.Tag'),
        ),
        migrations.AddField(
            model_name='review',
            name='related_book',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Book.Book'),
        ),
        migrations.AddField(
            model_name='review',
            name='writer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Account.UserInfo'),
        ),
    ]
