# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-24 17:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0008_auto_20160725_0054'),
        ('Book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='writer',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='Account.UserInfo'),
        ),
    ]
