# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-26 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_userinfo_collectionlist'),
        ('Book', '0002_auto_20160726_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='reviewList',
            field=models.ManyToManyField(default=[], through='Book.Review', to='Account.UserInfo'),
        ),
    ]
