# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-26 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0003_book_reviewlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pressTime',
            field=models.CharField(default='', max_length=40),
        ),
    ]
