# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-26 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0004_auto_20160726_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.CharField(default='', max_length=300),
        ),
    ]
