# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-26 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0005_auto_20160726_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='intro',
            field=models.CharField(default='', max_length=3000),
        ),
    ]
