# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-26 10:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('sendTime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('content', models.CharField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=50)),
                ('gender', models.CharField(default='male', max_length=10)),
                ('phone', models.IntegerField(default=0)),
                ('info', models.CharField(default='your information', max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('prevImage', models.ImageField(default='headImages/default.jpg', upload_to='headImages/')),
                ('headImage', models.ImageField(default='headImages/default.jpg', upload_to='headImages/')),
                ('score', models.FloatField(default=0)),
                ('isAdmin', models.BooleanField(default=False)),
                ('isBlocked', models.BooleanField(default=True)),
                ('followList', models.ManyToManyField(related_name='_userinfo_followList_+', to='Account.UserInfo')),
                ('noteList', models.ManyToManyField(to='Account.Note')),
                ('reveiveMessageList', models.ManyToManyField(related_name='messages_you_received', to='Account.Message')),
                ('sendMessageList', models.ManyToManyField(related_name='messages_you_send', to='Account.Message')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='relatedUser',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Account.UserInfo'),
        ),
    ]
