# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-26 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0001_initial'),
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='collectionList',
            field=models.ManyToManyField(to='Book.Book'),
        ),
    ]
