# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-23 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_auto_20160722_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='info',
            field=models.CharField(default='your information', max_length=255),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='isBlocked',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='phone',
            field=models.IntegerField(default=0),
        ),
    ]
