# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-28 01:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_remove_message_relateduser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='reveiveMessageList',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='sendMessageList',
        ),
        migrations.AddField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='Account.UserInfo'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='Account.UserInfo'),
        ),
    ]
