# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-28 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_auto_20160728_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='headImage',
            field=models.ImageField(default='headImages/default.jpg', upload_to='/static/headImages/'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='prevImage',
            field=models.ImageField(default='headImages/default.jpg', upload_to=b''),
        ),
    ]
