# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-24 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_auto_20160723_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='headImage',
            field=models.FileField(default=None, upload_to='/headimages/'),
        ),
    ]
