# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-24 16:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0007_auto_20160724_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('sendTime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('content', models.CharField(max_length=3000)),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='followList',
            field=models.ManyToManyField(related_name='_userinfo_followList_+', to='Account.UserInfo'),
        ),
        migrations.AddField(
            model_name='message',
            name='relatedUser',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Account.UserInfo'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='noteList',
            field=models.ManyToManyField(to='Account.Note'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='reveiveMessageList',
            field=models.ManyToManyField(related_name='messages_you_received', to='Account.Message'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='sendMessageList',
            field=models.ManyToManyField(related_name='messages_you_send', to='Account.Message'),
        ),
    ]
