# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-24 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0002_review_writer'),
        ('Account', '0008_auto_20160725_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='collectionList',
            field=models.ManyToManyField(to='Book.Book'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='reviewList',
            field=models.ManyToManyField(to='Book.Review'),
        ),
    ]
